// const char* root_cert = \
//   "-----BEGIN CERTIFICATE-----\n" \
//   "MIIEsTCCA5mgAwIBAgIQBOHnpNxc8vNtwCtCuF0VnzANBgkqhkiG9w0BAQsFADBs\n" \
//   "MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3\n" \
//   "d3cuZGlnaWNlcnQuY29tMSswKQYDVQQDEyJEaWdpQ2VydCBIaWdoIEFzc3VyYW5j\n" \
//   "ZSBFViBSb290IENBMB4XDTEzMTAyMjEyMDAwMFoXDTI4MTAyMjEyMDAwMFowcDEL\n" \
//   "MAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQd3d3\n" \
//   "LmRpZ2ljZXJ0LmNvbTEvMC0GA1UEAxMmRGlnaUNlcnQgU0hBMiBIaWdoIEFzc3Vy\n" \
//   "YW5jZSBTZXJ2ZXIgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC2\n" \
//   "4C/CJAbIbQRf1+8KZAayfSImZRauQkCbztyfn3YHPsMwVYcZuU+UDlqUH1VWtMIC\n" \
//   "Kq/QmO4LQNfE0DtyyBSe75CxEamu0si4QzrZCwvV1ZX1QK/IHe1NnF9Xt4ZQaJn1\n" \
//   "itrSxwUfqJfJ3KSxgoQtxq2lnMcZgqaFD15EWCo3j/018QsIJzJa9buLnqS9UdAn\n" \
//   "4t07QjOjBSjEuyjMmqwrIw14xnvmXnG3Sj4I+4G3FhahnSMSTeXXkgisdaScus0X\n" \
//   "sh5ENWV/UyU50RwKmmMbGZJ0aAo3wsJSSMs5WqK24V3B3aAguCGikyZvFEohQcft\n" \
//   "bZvySC/zA/WiaJJTL17jAgMBAAGjggFJMIIBRTASBgNVHRMBAf8ECDAGAQH/AgEA\n" \
//   "MA4GA1UdDwEB/wQEAwIBhjAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIw\n" \
//   "NAYIKwYBBQUHAQEEKDAmMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2Vy\n" \
//   "dC5jb20wSwYDVR0fBEQwQjBAoD6gPIY6aHR0cDovL2NybDQuZGlnaWNlcnQuY29t\n" \
//   "L0RpZ2lDZXJ0SGlnaEFzc3VyYW5jZUVWUm9vdENBLmNybDA9BgNVHSAENjA0MDIG\n" \
//   "BFUdIAAwKjAoBggrBgEFBQcCARYcaHR0cHM6Ly93d3cuZGlnaWNlcnQuY29tL0NQ\n" \
//   "UzAdBgNVHQ4EFgQUUWj/kK8CB3U8zNllZGKiErhZcjswHwYDVR0jBBgwFoAUsT7D\n" \
//   "aQP4v0cB1JgmGggC72NkK8MwDQYJKoZIhvcNAQELBQADggEBABiKlYkD5m3fXPwd\n" \
//   "aOpKj4PWUS+Na0QWnqxj9dJubISZi6qBcYRb7TROsLd5kinMLYBq8I4g4Xmk/gNH\n" \
//   "E+r1hspZcX30BJZr01lYPf7TMSVcGDiEo+afgv2MW5gxTs14nhr9hctJqvIni5ly\n" \
//   "/D6q1UEL2tU2ob8cbkdJf17ZSHwD2f2LSaCYJkJA69aSEaRkCldUxPUd1gJea6zu\n" \
//   "xICaEnL6VpPX/78whQYwvwt/Tv9XBZ0k7YXDK/umdaisLRbvfXknsuvCnQsH6qqF\n" \
//   "0wGjIChBWUMo0oHjqvbsezt3tkBigAVBRQHvFwY+3sAzm2fTYS5yh+Rp/BIAV0Ae\n" \
//   "cPUeybQ=\n" \
//   "-----END CERTIFICATE-----\n";


const char* root_cert = \
    "-----BEGIN CERTIFICATE REQUEST-----\n" \
    "MIICtzCCAZ8CAQAwcjELMAkGA1UEBhMCQ04xETAPBgNVBAgTCFpoZWppYW5nMREw\n" \
    "DwYDVQQHEwhIYW5nemhvdTE9MDsGA1UEAww0Z2l0ZWUuY29tL3N5c2RsMTMyL0No\n" \
    "YXRfQVBQX001U3RhY2svcmF3L21hc3Rlci8xLmJpbjCCASIwDQYJKoZIhvcNAQEB\n" \
    "BQADggEPADCCAQoCggEBAK0Ys3meeyFXAro7Tv9YklkeU+opocz25qx9W0EtpoN3\n" \
    "5TAv0NXAI9ibNBuswaNStvRQlE0dhdJXpMTi6MLAVI3fb7MIVeUvL0Lzxr+Pew9Y\n" \
    "4A6QAO0MwcSB8nI9Uyj3G9/vcpOmNfv/Ixb4jNndNRFV4NVkZBBIMOiTqP8dcJ6/\n" \
    "MnIujce2gKMX33YKaE2hEryeU3kjImkwPOmEQlJlW94mK5ZgB+pBIZn1kEQ62dLl\n" \
    "Hz2WzgZ+sWLfpErEFVYf5hrkHmSrcp/lYrWTVR5Snn2Kowb8kBF0BSmAp/5mSs2I\n" \
    "voALNJMiudFqxfbzQZKhCFnD/lPpBbw4Fhve7VU9/zMCAwEAAaAAMA0GCSqGSIb3\n" \
    "DQEBCwUAA4IBAQBGPubJwDgChqpLd21som8yAeIX0JZfKqAeTAHWkcrpnzkAC5YU\n" \
    "9hr+RX31QP6C0ykWrHzCM2uZRaI6dbaTTgpe3Ih+aTZVuEBrWdmBa7NnY/W046iW\n" \
    "/hzZ6iblxFh5F/f86wrXJcn4DMZpSw7YaQQINVo2AsY0mlrj+mrPtpZKLS7NVKtc\n" \
    "zGjJjG4OrjgaK7VjEHM096xd2qImR1ecJT/i+2d+2WXur9uAL2CJBVe+VWJwFlp+\n" \
    "GyGj2L7KlUmhDRkH2uY2rhI5QJoxO4BWHwAOk7BWzHPqs2tdohvfR1VgMDNxXbjG\n" \
    "/94alzMjhJ1u0NDZdLlKHcR0PzbLSoRNC5tt\n" \
    "-----END CERTIFICATE REQUEST-----\n";
